"""empty message

Revision ID: 61c3e9180e59
Revises: 8bcdb357bcf4
Create Date: 2020-10-29 10:47:09.882863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c3e9180e59'
down_revision = '8bcdb357bcf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_foreign_key(None, 'search', 'user', ['user_id'], ['id'])
    #op.drop_column('search', 'user')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('user', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'search', type_='foreignkey')
    # ### end Alembic commands ###
