"""empty message

Revision ID: f4d46a03db23
Revises: 10c5a6b933ba
Create Date: 2020-10-29 09:36:59.915997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d46a03db23'
down_revision = '10c5a6b933ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'search', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search', type_='foreignkey')
    # ### end Alembic commands ###
