"""empty message

Revision ID: b54212b71609
Revises: 8bcdb357bcf4
Create Date: 2020-10-31 11:04:33.348883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54212b71609'
down_revision = '8bcdb357bcf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price', type_='foreignkey')
    op.create_foreign_key(None, 'price', 'product', ['asin'], ['asin'], ondelete='cascade')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'search', ['search'], ['name'], ondelete='cascade')
    op.create_foreign_key(None, 'search', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.drop_column('search', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('user', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'search', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'search', ['search'], ['name'])
    op.drop_constraint(None, 'price', type_='foreignkey')
    op.create_foreign_key(None, 'price', 'product', ['asin'], ['asin'])
    # ### end Alembic commands ###
